public class RetailStoreListDTO {
    public String  storeId;
    public String  storeName;
    public String  city;
    public String  subArea;
    public Decimal footfallIndex;
    public Decimal currentDemandScore;
    public Decimal demographicScore;
    public Decimal ebitdaMargin;
    public Decimal paybackPeriodYears;
    public String retailLocationGroupId;
    public String retailLocationGroupName;
    public String retailLocationGroupArea;
    public String retailLocationGroupPincode;
    public List<SiteListDTO> sites;
}