public class SiteListDTO {
    public String  siteId;
    public String  siteName;
    public String  status;
    public Decimal competitionLevel;
    public Decimal competitionActivity;
    public Decimal competitionConfidence;
    public Decimal competitionImpact;
    public Decimal distanceKm;
    public Decimal latitude;
    public Decimal longitude;
    public String  retailStoreId;
    public String  retailStoreName;
    public String  retailStoreCity;
    public String  retailStoreSubArea;
    public List<SiteVisitDTO> visits;
}